### ISSUE TITLE
Broken LinkedIn profile link

### ISSUE THREAD

**Issue by kaustubhgupta** [Sam-Varghese/Sam-Varghese#9]
Hi,

I was discovering your profile and found that the LinkedIn contact points to this URL. "https://www.linkedin.com/feed/" 
![image](https://user-images.githubusercontent.com/43691873/123753011-00ec8180-d8d7-11eb-835e-4318bc028a83.png)

I think you need to fix it :)

Thanks

**Comment by Sam-Varghese** [comment]
@kaustubhgupta Thanks a lot for pointing out this issue. I would update my profile as soon as possible.

**Comment by Sam-Varghese** [comment]
I have corrected the LinkedIn link. Now it should work fine. Hence closing this issue.
